_BASE_: ../Base-bagtricks.yml

INPUT:                                                                                                                                                                                                                             
  AFFINE:
    ENABLED: True
  AUGMIX:
    ENABLED: False
    PROB: 0.0
  AUTOAUG:
    ENABLED: False
    PROB: 0.0
  CJ:
    BRIGHTNESS: 0.15
    CONTRAST: 0.25
    ENABLED: True
    HUE: 0.0
    PROB: 1.0
    SATURATION: 0.25
  CROP:
    ENABLED: True
    RATIO: [0.86, 1.15]
    SCALE: [0.88, 1]
    SIZE: [256, 256]
  FLIP:
    ENABLED: True
    PROB: 0.5
  PADDING:
    ENABLED: False
    MODE: constant
    SIZE: 10
  REA:
    ENABLED: True
    PROB: 0.5
    VALUE: [123.675, 116.28, 103.53]

  SIZE_TEST: [256, 256]
  SIZE_TRAIN: [256, 256]

MODEL:
  BACKBONE:
    WITH_IBN: True

  HEADS:
    POOL_LAYER: GeneralizedMeanPooling
  LOSSES:
    TRI:
      HARD_MINING: True
      MARGIN: 0.3
      SCALE: 10.

DATASETS:
  NAMES: ("VeRiWild",)
  TESTS: ("SmallVeRiWild", "MediumVeRiWild", "LargeVeRiWild",)

SOLVER:
  IMS_PER_BATCH: 140 # 512 For 4 GPUs
  MAX_EPOCH: 30
  STEPS: [10, 40, 90]
  WARMUP_ITERS: 5000

  CHECKPOINT_PERIOD: 5

  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_NORM: 0.0005

TEST:
  EVAL_PERIOD: 5
  IMS_PER_BATCH: 128

OUTPUT_DIR: logs/veriwild/cos03_scale10_longer
